# Generated by Django 5.2.5 on 2025-09-03 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start_rent', models.DateField(default=datetime.date.today)),
                ('deta_end_rent', models.DateField(default=datetime.date.today)),
                ('count_objects', models.PositiveIntegerField(default=0)),
                ('comment', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('rent_price', models.PositiveIntegerField(default=0)),
                ('period', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
