# Generated by Django 5.2.5 on 2025-09-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('location', models.CharField()),
                ('contacts', models.CharField(default='')),
                ('date_start_rent', models.DateTimeField(auto_now_add=True)),
                ('date_end_rent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
